# Generated by Django 3.0.2 on 2020-01-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0006_userprofile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
    ]
